### PR TITLE
Fix quest generation and regenerate data

### PR DESCRIPTION
**Pull request by lezed1**
New quest, who dis?

### CODE REVIEW

**Comment by jayktaylor** [comment]
It looks like this was fixed in https://github.com/weirdgloop/wikisync-api/commit/b7d77542eb5126dcea089c02ad4a91561069107c, is that correct?

**Comment by lezed1** [comment]
The main part of this PR was to get quest Varbit generation working again to support the new quest that was recently added. The music and combat achievement updates were side effects from rerunning the scripts to generate data.

**Comment by jayktaylor** [comment]
Should now be deployed

**Comment by lezed1** [comment]
Sweet, thanks!

**Pull request merged**
